name: 'Start Honey Server'
description: 'Starts the honey server in background and waits for it to be ready'

runs:
  using: 'composite'
  steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
      
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      
    - name: Confirm forge is installed
      shell: bash
      run: forge --version

    - name: Install supersim
      shell: bash
      run: |
        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        
        # Map architecture names
        case $ARCH in
          x86_64) ARCH="amd64" ;;
          arm64|aarch64) ARCH="arm64" ;;
        esac
        
        # Download and install supersim
        SUPERSIM_URL="https://github.com/ethereum-optimism/supersim/releases/download/0.1.0-alpha.55/supersim_0.1.0-alpha.55_${OS}_${ARCH}.tar.gz"
        echo "Downloading supersim from: $SUPERSIM_URL"
        curl -L -o supersim.tar.gz "$SUPERSIM_URL"
        tar -xzf supersim.tar.gz
        chmod +x supersim
        sudo mv supersim /usr/local/bin/
    
    - name: Confirm supersim is installed
      shell: bash
      run: supersim --version

    - name: Start honey server in background 
      shell: bash
      run: |
        cd packages/honey
        npm run build
        nohup npm run start > honey.log 2>&1 &
        echo "Honey server PID: $!"
        
        # Wait for "Honey is running" message in logs
        timeout=300  # 5 minutes timeout
        elapsed=0
        while [ $elapsed -lt $timeout ]; do
          if grep -q "Honey is running" honey.log; then
            echo "✅ Honey server is ready!"
            break
          fi
          sleep 5
          elapsed=$((elapsed + 5))
          echo "Waiting for honey server... (${elapsed}s/${timeout}s)"
        done
        
        if [ $elapsed -ge $timeout ]; then
          echo "❌ Timeout waiting for honey server to start"
          echo "Last 50 lines of honey.log:"
          tail -50 honey.log
          exit 1
        fi

    - name: Test fork
      shell: bash
      run: cast call 0x7F6D3A4c8a1111DDbFe282794f4D608aB7Cb23A2 "MAX_TOKENS()(uint256)" --rpc-url http://localhost:4444