name: Build and Release Sugar SDK

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build sugar-sdk
        run: |
          cd packages/sugar-sdk
          npm run build

      - name: Run Honey 🍯
        uses: ./.github/actions/honey
          
      - name: Run tests
        run: npm test
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Sugar SDK release ${{ github.ref_name }}
            
            Install via npm:
            ```
            npm install git+https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git#${{ github.ref_name }}
            ```